### Set Host
@host = http://localhost:8084/fhir

### 0. Get FHIR server metadata to see if up
GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+xml;fhirVersion=5.0.0-snapshot1
Origin: http://localhost


### 1. Get the CodeSystem dose-form-ontology-cs (to check the content is uploaded)

GET {{host}}/CodeSystem/dose-form-ontology-cs HTTP/1.1
Accept: application/json+fhir

### 


### TRANSACTION 3. Get all codes that are under a given dose form

@doseform = "10220000" 
##@doseform = "20053000"

POST {{host}}/ValueSet/$expand HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

{
    "resourceType": "Parameters",
    "parameter": [

        {
            "name": "valueSet",
            "resource": {
                "resourceType": "ValueSet",
                "url": "http://example.com/siblings",
                "title": "Sibling codes",
                "name": "Sibling_codes",
                "status": "draft",
                "compose": {
                    "include": [
                        {
                            "filter": [
                                {
                                    "property": "concept",
                                    "op": "is-a",
                                    "value": {{doseform}}
                                }
                            ],
                            "system": "http://medigree.net/fhir/ee/idmp/CodeSystem/dose-form-ontology-cs"
                        },
                        {
                            "concept": [
                                {
                                    "code": {{doseform}}
                                }
                            ],
                            "system": "http://medigree.net/fhir/ee/idmp/CodeSystem/dose-form-ontology-cs"
                        }

                    ]
                }
            }
        }
    ]
}

### TRANSACTION 8

GET {{host}}/MedicationKnowledge?dose-form=10318000,10220000
